CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT
  ,email STRING NOT NULL
  ,name STRING NOT NULL
  ,pass STRING NOT NULL
);


CREATE TABLE roll (
  id INTEGER PRIMARY KEY AUTOINCREMENT
  ,id_dice INTEGER NOT NULL
  ,id_user INTEGER NOT NULL
  ,value INTEGER NOT NULL
  ,FOREIGN KEY(id_user) REFERENCES user(id)
  ,FOREIGN KEY(id_dice ) REFERENCES dice(id)
);


CREATE TABLE dice (
  id INTEGER PRIMARY KEY AUTOINCREMENT
  ,type INTEGER NOT NULL
);


CREATE TABLE type_dice (
  id INTEGER PRIMARY KEY AUTOINCREMENT
  ,sides STRING NOT NULL
);
